export const SCORM_1X = {
    GENERAL_EXCEPTION: '101',
    INVALID_ARGUMENT_ERROR: '201',
    ELEMENT_CANNOT_HAVE_CHILDREN: '202',
    ELEMENT_NOT_AN_ARRAY_CANNOT_HAVE_COUNT: '203',
    NOT_INITIALIZED: '301',
    NOT_IMPLEMENTED_ERROR: '401',
    INVALID_SET_VALUE_ELEMENT_IS_A_KEYWORD: '402',
    ELEMENT_IS_READ_ONLY: '403',
    ELEMENT_IS_WRITE_ONLY: '404',
    INCORRECT_DATA_TYPE: '405'
};

export const SCORM_2004 = {
    GENERAL_EXCEPTION: '101',
    GENERAL_ARGUMENT_ERROR: '201',
    GENERAL_GET_FAILURE: '301',
    GENERAL_SET_FAILURE: '351',
    UNDEFINED_DATA_MODEL_ELEMENT: '401',
    UNIMPLEMENTED_DATA_MODEL_ELEMENT: '402',
    DATA_MODEL_ELEMENT_VALUE_NOT_INITIALIZED: '403',
    DATA_MODEL_ELEMENT_IS_READ_ONLY: '404',
    DATA_MODEL_ELEMENT_IS_WRITE_ONLY: '405',
    DATA_MODEL_ELEMENT_TYPE_MISMATCH: '406',
    DATA_MODEL_ELEMENT_VALUE_OUT_OF_RANGE: '407',
    DATA_MODEL_DEPENDENCY_NOT_ESTABLISHED: '408'
};
